/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'rwr_game.exe'
*/
#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 39 */
typedef unsigned int DWORD;

/* 229 */
struct __declspec(align(4)) EntityList
{
  int *this;
  int field_4;
  int field_8;
  int *begin;
  int *last_next;
  int *pointer_14;
  int *pointer_18;
  int field_1C;
  int field_20;
  int field_24;
  int field_28;
  int field_2C;
  int *pointer_30;
  int field_34;
};

/* 42 */
typedef unsigned __int8 BYTE;

/* 165 */
struct __declspec(align(8)) Game
{
  _BYTE gap0[12];
  int *GUIApplication;
  int *Verlet::ParticleSystem;
  DWORD *int14;
  _BYTE gap18[2516];
  EntityList Person_Entitylist;
  EntityList Fighter_Entitylist;
  EntityList StaticObject_Entitylist;
  _BYTE gapA94[405];
  int *World_c2c;
  int *Fog_c30;
  _BYTE gapC34[228];
  int *FighterInputHandler_d18;
  __declspec(align(8)) int AiSystem_d20;
  int *Interaction_d24;
  int *GameInput_d28;
  _BYTE gapD2C;
  BYTE debugmode_D2D;
  _BYTE gapD2E[46];
  int *Visual::Hud;
  _BYTE gapD60[32];
  int *WorldBlock;
  _BYTE gapD84[1212];
  int *TiXmlBase;
  _BYTE gap1244[232];
  int *UserStats;
  _BYTE gap1330[20];
  int *UserStats_;
  _BYTE gap1348[332];
  int *Crosshair;
  _BYTE gap1498[16];
  int *ChatLog;
  int *Visual::EffectSystem;
  int *Visual::Manager;
  _BYTE gap14B4[24];
  int Aural::Manager;
  _BYTE gap14D0[72];
  int *WorldSituation;
  _BYTE gap151C[52];
  BYTE no_simulation_1550;
  _BYTE gap1551[147];
  int *State;
  _BYTE gap15E8[68];
  int *ProfileManager;
  _BYTE gap1630[328];
  int *Ogre::SharedPtr_of_Ogre::ScriptToken;
  _BYTE gap177C[2276];
  BYTE lag_mode_2060;
  BYTE unknown2[443];
  BYTE antihack_221c;
};

/* 215 */
struct ConnectionOfServer
{
  _DWORD dword0;
  int *unknown_function;
  byte gap[4];
  float connect_server_timer_floatC;
  float retry_timer_float10;
};

/* 220 */
struct Network::Server
{
  _DWORD dword0;
  __declspec(align(8)) char *pGameConfigParams;
  __declspec(align(8)) int *pint10;
  _BYTE gap14[8];
  _DWORD dword1C;
  _DWORD dword20;
  _BYTE gap24[176];
  float floatD4;
  _BYTE gapD8[112];
  float float148;
  float float14C;
};

/* 221 */
struct MetaGameLauncherAngelScript
{
  _BYTE gap0[4];
  Game *pgameconfigparams4;
};

/* 222 */
struct GUIApplication
{
  _BYTE gap0[4];
  int Graphics;
  int Input;
  int Audio;
  int GUIUpdater;
  int Console;
  int MetaGameInterfaceAngelScript;
  _BYTE gap1C[24];
  int Game;
  _BYTE gap38[16];
  int GUIIntro;
  _BYTE gap4C[44];
  int AppDataWin32;
  _BYTE gap7C[256];
  int AsyncInfoServerAccess;
  _BYTE gap180[3711];
  byte gap2;
};

/* 224 */
struct __unaligned __declspec(align(1)) Fighter
{
  _BYTE gap0[128];
  _DWORD Game;
  _BYTE gap84[36];
  int field_A8;
  int Visual::Character;
  _BYTE gapB0[580];
  _DWORD Weapon;
  _BYTE gap2F8[28];
  _DWORD Person;
  _BYTE gap318[48];
  int RWR::Handle_of_Character;
  _BYTE gap34C[4];
  unsigned __int8 weapon_class;
};

/* 225 */
struct __unaligned __declspec(align(1)) Weapon
{
  _BYTE gap0[4];
  _DWORD last_burst_retrigger_time;
  _BYTE gap8[32];
  _BYTE class;
};

/* 226 */
struct Person
{
  _BYTE gap0[56];
  char dead;
  _BYTE gap39[159];
  int id;
  _BYTE gapDC[35];
  byte gap1;
};

/* 227 */
struct Console
{
  _BYTE gap0[36];
  int Audio;
  _BYTE gap28[88];
  int OIS::Win32InputManager;
  _BYTE gap84[1940];
  int TiXmlBase;
  _BYTE gap81C[72];
  int Graphics;
  _BYTE gap868[2239];
  char field_28;
};

/* 228 */
struct TiXmlElement
{
  int int0;
  _DWORD dword4;
  _DWORD dword8;
  _DWORD dwordC;
  _DWORD dword10;
  _DWORD dword14;
  _DWORD dword18;
  _DWORD dword1C;
  int int20;
  _DWORD dword24;
  _DWORD dword28;
  _DWORD dword2C;
  _DWORD dword30;
  _DWORD dword34;
  _DWORD dword38;
  _DWORD dword3C;
  _DWORD dword40;
  _DWORD dword44;
  _DWORD dword48;
  _DWORD dword4C;
};