/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'rwr_game.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 42 */
typedef unsigned __int8 BYTE;

/* 165 */
struct GameConfigParams
{
  BYTE unknown0[3373];
  BYTE debugmode_D2D;
  BYTE unknown1[5358];
  BYTE antihack_221c;
};

